export const BEGIN_GET_USERDATA = 'GETUSERDATA';
export const GET_USERDATA_OK = 'GET_USERDATA_OK';
export const GET_USERDATA_ERROR = 'GET_USERDATA_ERROR';

export const COMIENZA_LOGIN = 'COMIENZA_LOGIN';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';
export const OCULTAR_ERROR = 'OCULTAR_ERROR';

export const MOSTRAR_USUARIO = 'MOSTRAR_USUARIO';
export const MOSTRAR_CREA_USUARIO = 'MOSTRAR_CREA_USUARIO';

export const OBTIENE_ALL_USERS = 'OBTIENE_ALL_USERS';
export const CREA_USUARIOS_EXITO = 'CREA_USUARIOS_EXITO';

export const CERRAR_SESION = 'CERRAR_SESION';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
